### ISSUE TITLE
apollo-resolvers as subscription "subscribe"

### ISSUE THREAD

**Issue by groundmuffin** [thebigredgeek/apollo-resolvers#41]
Hi,
is it possible to use apollo-resolvers as subscription resolver?

I noticed in this case the context is not passed to resolver.

```
export const resolvers = {
	//...
	Subscription: {
		status: {
			subscribe:
				isAuthenticatedResolver.createResolver(
					(_, args, context, info) => {
						//...
					}
				),
			resolve: ({ data }) =>
				//...
		}
	}
};
```

**Comment by mringer** [comment]
That would happen upstream from apollo-resolvers but if you're using [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions) then [Payload Manipulation](https://github.com/apollographql/graphql-subscriptions#payload-manipulation) is probably what you're looking for.

Basically you'd need to provide a separate resolve function such as created by createResolver in addition to the subscribe function, rather than trying to pass the context through the subscribe method itself.

You could declare your resolvers separately and simply reuse them if you have resolvers which need to subscribe or simply return a promise.

**Comment by groundmuffin** [comment]
Thank you for help!
